version: '3'
services:
  elasticsearch:
    image: opensearchproject/opensearch:2.5.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - .:/opensearch-analysis-thaichub2
    command: sh -c './bin/opensearch-plugin install --batch file:///opensearch-analysis-thaichub2/target/releases/analysis-thaichub2-2.5.0.zip && exec /usr/local/bin/docker-entrypoint.sh opensearch'
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.5.0
    container_name: opensearch-dashboards
    depends_on:
      - opensearch
    ports:
      - 5601:5601
    links:
      - opensearch:opensearch
